### ISSUE TITLE
BUG: RLP Status shows incorrect info for WASM Plugin and envoy

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/kuadrant-operator#982] opened 2024-11-06 10:09 UTC
### WHAT:
```
message: 'RateLimitPolicy waiting for the following components to sync: [EnvoyFilter
      (kuadrant-system/internal-external) WasmPlugin (kuadrant-system/internal-external)]'
    reason: Unknown
    status: "False"
    type: Enforced 
```
Logs:
https://gist.github.com/R-Lawton/2ca126f405391268ec136f2c33b84d0d

**Comment by guicassolato** [comment] 2024-11-06 13:06
I cannot reproduce this bug 😞

I've tried 3 different ways:

1. Sail Operator (and freshly built Operator image)
    ```
    make local-setup
    ```
2. Istio Operator (and freshly built Operator image)
    ```sh
    make local-setup ISTIO_INSTALL_SAIL=false
    ```
3. Bare Istio (and `quay.io/kuadrant/kuadrant-operator:latest`)
    ```sh
    kind create cluster --name kuadrant-local
    kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml
    curl -sL https://istio.io/downloadIstio | ISTIO_VERSION=1.23.2 sh -
    istio-1.23.2/bin/istioctl install --set profile=minimal
    make deploy-istio-gateway
    make k8s-env-setup
    make deploy
    ```

<br>

I then created the resources:

```sh
kubectl apply -f examples/toystore/toystore.yaml

kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: toystore
spec:
  parentRefs:
  - name: kuadrant-ingressgateway
    namespace: gateway-system
  hostnames:
  - api.toystore.io
  rules:
  - backendRefs:
    - name: toystore
      port: 80
EOF
```

```sh
kubectl -n kuadrant-system apply -f - <<EOF
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant
spec: {}
EOF
```

```sh
kubectl apply -f - <<EOF
apiVersion: kuadrant.io/v1beta3
kind: RateLimitPolicy
metadata:
  name: toystore-rl
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
  limits:
    global:
      rates:
      - limit: 2
        duration: 10
        unit: second
EOF
```

Every single time, the status of the policy moves to `Enforced: true` about 1-2s after it is created. E.g.:

```yaml
apiVersion: kuadrant.io/v1beta3
kind: RateLimitPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kuadrant.io/v1beta3","kind":"RateLimitPolicy","metadata":{"annotations":{},"name":"toystore-rl","namespace":"default"},"spec":{"limits":{"global":{"rates":[{"duration":10,"limit":2,"unit":"second"}]}},"targetRef":{"group":"gateway.networking.k8s.io","kind":"HTTPRoute","name":"toystore"}}}
  creationTimestamp: "2024-11-06T11:42:07Z"
  generation: 1
  name: toystore-rl
  namespace: default
  resourceVersion: "6808"
  uid: 46dfe259-2649-4658-88dc-eea527ec1060
spec:
  limits:
    global:
      rates:
        - duration: 10
          limit: 2
          unit: second
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
status:
  conditions:
    - lastTransitionTime: "2024-11-06T11:42:07Z"
      message: RateLimitPolicy has been accepted
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-11-06T11:42:09Z"
      message: RateLimitPolicy has been successfully enforced
      reason: Enforced
      status: "True"
      type: Enforced
  observedGeneration: 1
```

**Comment by azgabur** [comment] 2024-11-06 14:37
I encountered same behavior on Openshift with Sail operator 0.1.0 and Istio v1.23.0 deployed. The EnvoyFilter and WasmPlugin CR's were missing as well.

**Comment by R-Lawton** [comment] 2024-11-07 11:37
a lot of things have changed in the last few days so i updated my branch and its all better now 😄

**Comment by guicassolato** [comment] 2024-11-11 14:54
What's the status of this? Can we perhaps close it?

**Closed** 2024-11-11 16:29 UTC
