### ISSUE TITLE
Include the traceID (& parent trace id if available) in logs

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/kuadrant-operator#438] opened 2024-02-27 16:59 UTC
WHAT:  Include TraceID in data plane component logs when tracing is enabled.

WHY: To allow logs to be correlated to tracing information for specific requests

- [x] TraceID in limitador
- [ ] TraceID in authorino
- [ ] TraceID in wasm-shim

**Comment by david-martin** [comment] 2024-04-05 15:47
This is already the case for limitador:

```
"Request received: Request { metadata: MetadataMap { headers: {"te": "trailers", "grpc-timeout": "5000m", "content-type": "application/grpc", "traceparent": "00-4a2a933a23df267aed612f4694b32141-00f067aa0ba902b7-01", "x-envoy-internal": "true", "x-envoy-expected-rq-timeout-ms": "5000"} }, message: RateLimitRequest { domain: "default/toystore", descriptors: [RateLimitDescriptor { entries: [Entry { key: "limit.general_user__f5646550", value: "1" }, Entry { key: "metadata.filter_metadata.envoy\\.filters\\.http\\.ext_authz.identity.userid", value: "alice" }], limit: None }], hits_addend: 1 }, extensions: Extensions }"
```

@guicassolato do you know if the traceid is logged out in authorino (even if log levels need to be increased)?

**Comment by guicassolato** [comment] 2024-04-11 15:05
> > which _in the traces_ will link to the trace id as a fixed attribute of all traces generated in the request flow
> 
> Thanks @guicassolato I'm wondering what the flow is for someone debugging and wanting to make the link between a trace and authorino logs. Would they start with tracing, and see some 'tag' on the trace with the request id, then find that in authorino logs? Or is it the other way around somehow?
> 
> Where I'm coming from here is having some info about how you might use tracing e2e to troubleshoot a request.

If you have both enabled (tracing and logs), I supposed it doesn't really matter if you start from one of the other. I imagine the problem is when you don't have tracing enabled in Authorino, then the request id is pretty much useless, unless you also check the gateway logs where request id and the trace id must also show up linked together.

Probably, the best thing to do is make sure the trace id is present in the Authorino logs and avoid all this trouble.

**Comment by david-martin** [comment] 2024-04-22 14:25
Thanks @guicassolato 
I'm closing this out with the information given.
That can be taken into account with the related docs issue for a tracing guide https://github.com/Kuadrant/docs.kuadrant.io/issues/70

**Closed by david-martin** 2024-04-22 14:25 UTC
